### PR TITLE
Release 0.6.7

### PR DESCRIPTION
**Pull request by jakirkham**
Partially addresses issue ( https://github.com/conda-forge/libgpuarray-feedstock/issues/2 ).

* Releases `libgpuarray` 0.6.7.
* Change the recipe to only build the C library (no longer build Python).
* Re-render with `conda-smithy` 2.3.2 to regenerate the CI matrices.

Note: After this is merged and released, the CIs of PR ( https://github.com/conda-forge/pygpu-feedstock/pull/1 ) should be restarted.

### CODE REVIEW

**Comment by jakirkham** [comment]
Appears there is a build issue with the latest version on Windows with Python 2.7. In particular, this [line]( https://github.com/Theano/libgpuarray/pull/447/files#diff-53b56c78c0960e451bcefee7a36f23aeR107 ) seems to be causing issues. Left a [comment]( https://github.com/Theano/libgpuarray/pull/447/files#r123865719 ) explaining the difficulty.

Edit: Also raised issue ( https://github.com/Theano/libgpuarray/issues/461 ) upstream.

**Comment by jakirkham** [comment]
Added a patch based on the diff from PR ( https://github.com/Theano/libgpuarray/pull/460 ) to workaround the Windows VS 2008 issues.

**Comment by jakirkham** [comment]
If you have time @abergeron, could you please take a look?

**Comment by abergeron** [comment]
I'm ok with this, but instead of the patch we could jump to 0.6.8 (which was released just now) and includes the windows build fix.

**Comment by jakirkham** [comment]
Sorry didn't know that soon meant today. Will open a new PR using the new release.

**Comment by jakirkham** [comment]
Replaced with PR ( https://github.com/conda-forge/libgpuarray-feedstock/pull/7 ), which updates to 0.6.8.

**Pull request closed without merging**
